# Generated by Django 4.1.3 on 2022-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_ID', models.CharField(max_length=20)),
                ('FName', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=25)),
                ('LName', models.CharField(max_length=20)),
                ('DoB', models.DateField()),
                ('registered', models.DateTimeField(auto_now=True)),
                ('DoD', models.DateField()),
            ],
        ),
    ]
