# Generated by Django 4.1.3 on 2022-12-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple_Family',
            fields=[
                ('Couple_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Wife', models.CharField(max_length=20, unique=True, null=False)),
                ('Wed_ann', models.DateField(null=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(max_length=100,null=False)),
                ('Venue', models.CharField(max_length=100,null=False)),
                ('Date', models.DateField(null=False)),
            ],
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('Family_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Fam_Name', models.CharField(max_length=50)),
                ('Members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('FamMemberID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=30,null=False)),
                ('Name', models.CharField(max_length=30,null=False)),
                ('Lname', models.CharField(max_length=30,null=False)),
                ('DoB', models.DateField(null=False)),
                ('DoD', models.DateField()),
                ('Gender', models.CharField(max_length=2,null=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('member_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='famapp.family_member')),
                ('Ph_prefix', models.IntegerField(null=False)),
                ('Phone', models.BigIntegerField(null=False)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254,null=False)),
                ('Job_or_student', models.CharField(max_length=50)),
                ('Company_or_School', models.CharField(max_length=50)),
                ('privilege', models.BooleanField(null=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Couple_invited', models.ManyToManyField(to='famapp.couple_family')),
                ('Event_code', models.ManyToManyField(to='famapp.events')),
                ('Family_invited', models.ManyToManyField(to='famapp.families')),
            ],
        ),
        migrations.AddField(
            model_name='couple_family',
            name='Hus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='famapp.family_member',null=False,unique=True),
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('child_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, unique=True, serialize=False, to='famapp.family_member')),
                ('parents_ID', models.ManyToManyField(to='famapp.couple_family',null=False)),
            ],
        ),
    ]
