# Generated by Django 4.1.3 on 2023-01-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple_Family',
            fields=[
                ('Couple_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Wed_ann', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Event_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Event_Name', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('Family_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Fam_Name', models.CharField(max_length=50)),
                ('Members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('FamMemberID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('DoB', models.DateField()),
                ('DoD', models.DateField(null=True)),
                ('Gender', models.CharField(max_length=2)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('member_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='famapp.family_member')),
                ('Ph_prefix', models.CharField(max_length=6)),
                ('Phone', models.CharField(max_length=18)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Pincode', models.CharField(max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Job_or_student', models.CharField(max_length=50)),
                ('Company_or_School', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('child_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='famapp.family_member')),
                ('parents_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='famapp.couple_family')),
            ],
        ),
        migrations.CreateModel(
            name='Invitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Couple_invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.couple_family')),
                ('Event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famapp.events')),
                ('Family_invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.families')),
            ],
        ),
        migrations.AddField(
            model_name='couple_family',
            name='Hus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='famapp.family_member'),
        ),
        migrations.AddField(
            model_name='couple_family',
            name='Wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='famapp.family_member'),
        ),
    ]
