# Generated by Django 4.1.3 on 2022-12-30 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_member',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couple_family',
            name='Wife',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='families',
            name='Fam_Name',
            field=models.CharField(max_length=50),
        ),
    ]
