# Generated by Django 4.1.3 on 2022-12-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0002_alter_couple_family_wife_alter_families_fam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_member',
            name='Password',
        ),
    ]
