# Generated by Django 4.1.3 on 2022-12-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0002_family_member_registered_on_alter_couple_family_wife_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Phone',
            field=models.CharField(max_length=18),
        ),
    ]
