# Generated by Django 4.1.3 on 2023-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0002_alter_parents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Event_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
