# Generated by Django 4.1.3 on 2022-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0002_alter_parents_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple_family',
            name='Wife',
            field=models.CharField(max_length=20),
        ),
    ]
