# Generated by Django 4.1.3 on 2023-01-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0003_alter_events_event_id_alter_parents_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitees',
            name='Member_Invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.family_member'),
        ),
    ]
