# Generated by Django 4.1.3 on 2023-01-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0004_invitees_member_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleInvited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Couple_invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.couple_family')),
                ('Event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInvited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famapp.events')),
                ('Family_invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.families')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInvited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='famapp.events')),
                ('Member_Invited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='famapp.family_member')),
            ],
        ),
        migrations.DeleteModel(
            name='Invitees',
        ),
    ]
