# Generated by Django 4.1.3 on 2022-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0004_alter_personal_info_ph_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='privilege',
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='Company_or_School',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='Job_or_student',
            field=models.CharField(max_length=50),
        ),
    ]
