# Generated by Django 4.1.3 on 2023-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0005_remove_personal_info_privilege_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='Pincode',
            field=models.CharField(max_length=15, null=False),
        ),
    ]
