# Generated by Django 4.1.3 on 2023-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0006_personal_info_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='Pincode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
