# Generated by Django 4.1.3 on 2023-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famapp', '0007_alter_personal_info_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='parents_ID',
        ),
        migrations.AddField(
            model_name='parents',
            name='parents_ID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
